[package]
name = "tokio-messaging"
version = "0.0.1"
edition = "2021"

[dependencies]
lazy_static = "1.4"
num-traits = "0.2"
tokio = { version = "1.21", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
